version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: donda
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/donda
      - JWT_SECRET=your_jwt_secret
      - OPENAI_API_KEY=your_openai_key
      - CORS_ORIGIN=http://localhost:3000
      - PORT=5000
    ports:
      - '5000:5000'
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://backend:5000
      - VITE_WS_URL=ws://backend:5000
      - VITE_APP_NAME=Donda
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  pgdata: